CORS Configuration
hanna-eismant/doky pull request #38
Opened 2023-02-02 20:51 UTC by Gooz92

Configured to allow requests to all endpoints from all origins.

Not very secure :)

2023-02-08 16:04 UTC, hanna-eismant requested changes

2023-02-08 16:04 UTC, hanna-eismant commented on server/src/main/java/org/hkurh/doky/DokyApplication.java
> +    public WebMvcConfigurer corsConfigurer() {
It is better to keep all security configutation in one place. Enable CORS in `org.hkurh.doky.security.WebSecurityConfig#configure` and create in this config bean `CorsConfigurationSource`.

2023-02-21 18:53 UTC, hanna-eismant requested changes

2023-02-21 18:53 UTC, hanna-eismant commented on server/src/main/java/org/hkurh/doky/DokyApplication.java
> +    public WebMvcConfigurer corsConfigurer() {
https://stackoverflow.com/questions/36968963/how-to-configure-cors-in-a-spring-boot-spring-security-application

2023-02-22 19:22 UTC, Gooz92 commented
@hanna-eismant Please note that WebSecurityConfigurerAdapter is deprecated 

https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter

2023-02-22 19:27 UTC, hanna-eismant approved these changes

2023-03-04 08:24 UTC, merged